export enum PokemonType {
    NORMAL = "normal",
    FIGHTING = "fighting",
    FLYING = "flying",
    POISON = "poison",
    GROUND = "ground",
    ROCK = "rock",
    BUG = "bug",
    GHOST = "ghost",
    STEEL = "steel",
    FIRE = "fire",
    WATER = "water",
    GRASS = "grass",
    ELECTRIC = "electric",
    PSYCHIC = "psychic",
    ICE = "ice",
    DRAGON = "dragon",
    DARK = "dark",
    FAIRY = "fairy",
}

export enum Game {
    RED = "Red",
    BLUE = "Blue",
    YELLOW = "Yellow",
    GOLD = "Gold",
    SILVER = "Silver",
    CRYSTAL = "Crystal",
    RUBY = "Ruby",
    SAPPHIRE = "Sapphire",
    EMERALD = "Emerald",
    FIRERED = "FireRed",
    LEAFGREEN = "LeafGreen",
    DIAMOND = "Diamond",
    PEARL = "Pearl",
    PLATINUM = "Platinum",
    HEARTGOLD = "HeartGold",
    SOULSILVER = "SoulSilver",
    BLACK = "Black",
    WHITE = "White",
    BLACK_2 = "Black 2",
    WHITE_2 = "White 2",
    X = "X",
    Y = "Y",
    OMEGA_RUBY = "Omega Ruby",
    ALPHA_SAPPHIRE = "Alpha Sapphire",
    SUN = "Sun",
    MOON = "Moon",
    ULTRA_SUN = "Ultra Sun",
    ULTRA_MOON = "Ultra Moon",
    LETS_GO_PIKACHU = "Lets Go Pikachu",
    LETS_GO_EEVEE = "Lets Go Eevee",
    SWORD = "Sword",
    SHIELD = "Shield",
    BRILLIANT_DIAMOND = "Brilliant Diamond",
    SHINING_PEARL = "Shining Pearl",
    LEGENDS_ARCEUS = "Legends: Arceus",
    SCARLET = "Scarlet",
    VIOLET = "Violet"
}

export enum VersionGroup {
    RED_BLUE = "Red/Blue",
    YELLOW = "Yellow",
    GOLD_SILVER = "Gold/Silver",
    CRYSTAL = "Crystal",
    RUBY_SAPPHIRE = "Ruby/Sapphire",
    EMERALD = "Emerald",
    FIRERED_LEAFGREEN = "FireRed/LeafGreen",
    DIAMOND_PEARL = "Diamond/Pearl",
    PLATINUM = "Platinum",
    HEARTGOLD_SOULSILVER = "HeartGold/SoulSilver",
    BLACK_WHITE = "Black/White",
    BLACK_2_WHITE_2 = "Black 2/White 2",
    X_Y = "X/Y",
    OMEGA_RUBY_ALPHA_SAPPHIRE = "Omega Ruby/Alpha Sapphire",
    SUN_MOON = "Sun/Moon",
    ULTRA_SUN_ULTRA_MOON = "Ultra Sun/Ultra Moon",
    LETS_GO_PIKACHU_LETS_GO_EEVEE = "Lets Go Pikachu/Lets Go Eevee",
    SWORD_SHIELD = "Sword/Shield",
    BRILLIANT_DIAMOND_AND_SHINING_PEARL = "Brilliant Diamond/Shining Pearl",
    LEGENDS_ARCEUS = "Legends: Arceus",
    SCARLET_VIOLET = "Scarlet/Violet"
}

export enum PokedexRegion {
    NATIONAL = "national",
    KANTO = "kanto",
    ORIGINAL_JOHTO = "original-Johto",
    HOENN = "hoenn",
    ORIGINAL_SINNOH = "original-sinnoh",
    EXTENDED_SINNOH = "extended-sinnoh",
    UPDATED_JOHTO = "updated-johto",
    ORIGINAL_UNOVA = "original-unova",
    UPDATED_UNOVA = "updated-unova",
    KALOS_CENTRAL = "kalos-central",
    KALOS_COASTAL = "kalos-coastal",
    KALOS_MOUNTAIN = "kalos-mountain",
    UPDATED_HOENN = "updated-hoenn",
    ORIGINAL_ALOLA = "original-alola",
    ORIGINAL_MELEMELE = "original-melemele",
    ORIGINAL_AKALA = "original-akala",
    ORIGINAL_ULAULA = "original-ulaula",
    ORIGINAL_PONI = "original-poni",
    UPDATED_ALOLA = "updated-alola",
    UPDATED_MELEMELE = "updated-melemele",
    UPDATED_AKALA = "updated-akala",
    UPDATED_ULAULA = "updated-ulaula",
    UPDATED_PONI = "updated-poni",
    LETSGO_KANTO = "letsgo-kanto",
    GALAR = "galar",
    ISLE_OF_ARMOR = "isle-of-armor",
    CROWN_TUNDRA = "crown-tundra",
    HISUI = "hisui",
    PALDEA = "paldea",
    KITAKAMI = "kitakami",
    BLUEBERRY = "blueberry"
}

export enum LearnMethod {
    LEVEL_UP = "Level Up",
    MACHINE = "Machine",
    TUTOR = "Tutor",
    EGG = "Egg",
    LIGHT_BALL_EGG = "Light Ball Egg",
    FORM_CHANGE = "Form Change",
    ZYGARDE_CUBE = "Zygarde Cube"
}

export enum MoveClass {
    PHYSICAL = "physical",
    SPECIAL = "special",
    STATUS = "status"
}