export enum PokemonType {
    NORMAL = "normal",
    FIGHTING = "fighting",
    FLYING = "flying",
    POISON = "poison",
    GROUND = "ground",
    ROCK = "rock",
    BUG = "bug",
    GHOST = "ghost",
    STEEL = "steel",
    FIRE = "fire",
    WATER = "water",
    GRASS = "grass",
    ELECTRIC = "electric",
    PSYCHIC = "psychic",
    ICE = "ice",
    DRAGON = "dragon",
    DARK = "dark",
    FAIRY = "fairy",
}

export enum Game {
    RED = "Red",
    BLUE = "Blue",
    YELLOW = "Yellow",
    GOLD = "Gold",
    SILVER = "Silver",
    CRYSTAL = "Crystal",
    RUBY = "Ruby",
    SAPPHIRE = "Sapphire",
    EMERALD = "Emerald",
    FIRERED = "FireRed",
    LEAFGREEN = "LeafGreen",
    DIAMOND = "Diamond",
    PEARL = "Pearl",
    PLATINUM = "Platinum",
    HEARTGOLD = "HeartGold",
    SOULSILVER = "SoulSilver",
    BLACK = "Black",
    WHITE = "White",
    BLACK_2 = "Black 2",
    WHITE_2 = "White 2",
    X = "X",
    Y = "Y",
    OMEGA_RUBY = "Omega Ruby",
    ALPHA_SAPPHIRE = "Alpha Sapphire",
    SUN = "Sun",
    MOON = "Moon",
    ULTRA_SUN = "Ultra Sun",
    ULTRA_MOON = "Ultra Moon",
    LETS_GO_PIKACHU = "Lets Go Pikachu",
    LETS_GO_EEVEE = "Lets Go Eevee",
    SWORD = "Sword",
    SHIELD = "Shield",
    BRILLIANT_DIAMOND = "Brilliant Diamond",
    SHINING_PEARL = "Shining Pearl",
    LEGENDS_ARCEUS = "Legends: Arceus",
    SCARLET = "Scarlet",
    VIOLET = "Violet"
}

export enum VersionGroup {
    RED_BLUE = "Red/Blue",
    YELLOW = "Yellow",
    GOLD_SILVER = "Gold/Silver",
    CRYSTAL = "Crystal",
    RUBY_SAPPHIRE = "Ruby/Sapphire",
    EMERALD = "Emerald",
    FIRERED_LEAFGREEN = "FireRed/LeafGreen",
    DIAMOND_PEARL = "Diamond/Pearl",
    PLATINUM = "Platinum",
    HEARTGOLD_SOULSILVER = "HeartGold/SoulSilver",
    BLACK_WHITE = "Black/White",
    BLACK_2_WHITE_2 = "Black 2/White 2",
    X_Y = "X/Y",
    OMEGA_RUBY_ALPHA_SAPPHIRE = "Omega Ruby/Alpha Sapphire",
    SUN_MOON = "Sun/Moon",
    ULTRA_SUN_ULTRA_MOON = "Ultra Sun/Ultra Moon",
    LETS_GO_PIKACHU_LETS_GO_EEVEE = "Lets Go Pikachu/Lets Go Eevee",
    SWORD_SHIELD = "Sword/Shield",
    BRILLIANT_DIAMOND_AND_SHINING_PEARL = "Brilliant Diamond/Shining Pearl",
    LEGENDS_ARCEUS = "Legends: Arceus",
    SCARLET_VIOLET = "Scarlet/Violet"
}

export enum PokedexRegion {
    NATIONAL = "National",
    KANTO = "Kanto",
    ORIGINAL_JOHTO = "Original Johto",
    HOENN = "Hoenn",
    ORIGINAL_SINNOH = "Original Sinnoh",
    EXTENDED_SINNOH = "Extended Sinnoh",
    UPDATED_JOHTO = "Updated Johto",
    ORIGINAL_UNOVA = "Original Unova",
    UPDATED_UNOVA = "Updated Unova",
    KALOS_CENTRAL = "Kalos Central",
    KALOS_COASTAL = "Kalos Coastal",
    KALOS_MOUNTAIN = "Kalos Mountain",
    UPDATED_HOENN = "Updated Hoenn",
    ORIGINAL_ALOLA = "Original Alola",
    ORIGINAL_MELEMELE = "Original Melemele",
    ORIGINAL_AKALA = "Original Akala",
    ORIGINAL_ULAULA = "Original Ulaula",
    ORIGINAL_PONI = "Original Poni",
    UPDATED_ALOLA = "Updated Alola",
    UPDATED_MELEMELE = "Updated Melemele",
    UPDATED_AKALA = "Updated Akala",
    UPDATED_ULAULA = "Updated Ulaula",
    UPDATED_PONI = "Updated Poni",
    LETSGO_KANTO = "Lets Go Kanto",
    GALAR = "Galar",
    ISLE_OF_ARMOR = "Isle of Armor",
    CROWN_TUNDRA = "Crown Tundra",
    HISUI = "Hisui",
    PALDEA = "Paldea",
    KITAKAMI = "Kitakami",
    BLUEBERRY = "Blueberry"
}

export enum LearnMethod {
    LEVEL_UP = "Level Up",
    MACHINE = "Machine",
    TUTOR = "Tutor",
    EGG = "Egg",
    LIGHT_BALL_EGG = "Light Ball Egg",
    FORM_CHANGE = "Form Change",
    ZYGARDE_CUBE = "Zygarde Cube"
}

export enum MoveClass {
    PHYSICAL = "physical",
    SPECIAL = "special",
    STATUS = "status"
}