import {Game, PokedexRegion} from "../../../global/enums.ts";

export const DexToRegionMapping: Partial<Record<PokedexRegion, string>> = {
    [PokedexRegion.KANTO]: 'Kanto',
    [PokedexRegion.LETSGO_KANTO]: 'Kanto',
    [PokedexRegion.ORIGINAL_JOHTO]: 'Johto',
    [PokedexRegion.UPDATED_JOHTO]: 'Johto',
    [PokedexRegion.HOENN]: 'Hoenn',
    [PokedexRegion.UPDATED_HOENN]: 'Hoenn',
    [PokedexRegion.ORIGINAL_SINNOH]: 'Sinnoh',
    [PokedexRegion.EXTENDED_SINNOH]: 'Sinnoh Pt',
    [PokedexRegion.ORIGINAL_UNOVA]: 'Unova',
    [PokedexRegion.UPDATED_UNOVA]: 'Unova',
    [PokedexRegion.KALOS_CENTRAL]: 'Kalos',
    [PokedexRegion.KALOS_COASTAL]: 'Kalos',
    [PokedexRegion.KALOS_MOUNTAIN]: 'Kalos',
    [PokedexRegion.ORIGINAL_ALOLA]: 'Alola',
    [PokedexRegion.UPDATED_ALOLA]: 'Alola',
    [PokedexRegion.GALAR]: 'Galar',
    [PokedexRegion.ISLE_OF_ARMOR]: 'Isle of Armor',
    [PokedexRegion.CROWN_TUNDRA]: 'Crown Tundra',
    [PokedexRegion.HISUI]: 'Hisui',
    [PokedexRegion.PALDEA]: 'Paldea',
    [PokedexRegion.KITAKAMI]: 'Kitakami',
    [PokedexRegion.BLUEBERRY]: 'Blueberry'
}


export const genToColorMap: Record<number, string> = {
    1: "#b4d279",
    2: "#dbd684",
    3: "#a8d5c8",
    4: "#b4a4c1",
    5: "#a8c9dd",
    6: "#ce688b",
    7: "#dc9887",
    8: "#be80bc",
    9: "#e4c28a",
}

export const regionToColorMap: Record<string, string> = {
    "Kanto": "#b4d279",
    "Johto": "#dbd684",
    "Hoenn": "#a8d5c8",
    "Sinnoh": "#b4a4c1",
    "Sinnoh Pt": "#b4a4c1",
    "Unova": "#a8c9dd",
    "Unova BW": "#a8c9dd",
    "Unova B2W2": "#a8c9dd",
    "Kalos": "#ce688b",
    "Kalos Central": "#ce688b",
    "Kalos Coastal": "#ce688b",
    "Kalos Mountain": "#ce688b",
    "Alola": "#dc9887",
    "Alola SM": "#dc9887",
    "Alola USUM": "#dc9887",
    "Galar": "#be80bc",
    "Isle of Armor": "#be80bc",
    "Crown Tundra": "#be80bc",
    "Hisui": "#8092a7",
    "Paldea": "#e4c28a",
    "Kitakami": "#75c1ba",
    "Blueberry": "#6386a4",
}

export const gameToColorMap: Record<Game, string> = {
    [Game.RED]: "#d43d40",
    [Game.BLUE]: "#364fd0",
    [Game.YELLOW]: "#f9d857",
    [Game.GOLD]: "#d2a741",
    [Game.SILVER]: "#c0c0c0",
    [Game.CRYSTAL]: "#78d6fb",
    [Game.RUBY]: "#bc353c",
    [Game.SAPPHIRE]: "#4150a1",
    [Game.EMERALD]: "#429459",
    [Game.FIRERED]: "#e0662a",
    [Game.LEAFGREEN]: "#acda44",
    [Game.DIAMOND]: "#aaa9f8",
    [Game.PEARL]: "#f2adab",
    [Game.PLATINUM]: "#999999",
    [Game.HEARTGOLD]: "#b29e33",
    [Game.SOULSILVER]: "#c0bfdd",
    [Game.BLACK]: "#444444",
    [Game.WHITE]: "#e1e1e1",
    [Game.BLACK_2]: "#444b4f",
    [Game.WHITE_2]: "#dfcfd0",
    [Game.X]: "#275ca1",
    [Game.Y]: "#d73645",
    [Game.OMEGA_RUBY]: "#9d3420",
    [Game.ALPHA_SAPPHIRE]: "#376398",
    [Game.SUN]: "#e49644",
    [Game.MOON]: "#6597c6",
    [Game.ULTRA_SUN]: "#d8643b",
    [Game.ULTRA_MOON]: "#396bb0",
    [Game.LETS_GO_PIKACHU]: "#f0db52",
    [Game.LETS_GO_EEVEE]: "#ca9557",
    [Game.SWORD]: "#479fe3",
    [Game.SHIELD]: "#af2450",
    [Game.BRILLIANT_DIAMOND]: "#67b8e1",
    [Game.SHINING_PEARL]: "#cd8299",
    [Game.LEGENDS_ARCEUS]: "#3e5878",
    [Game.SCARLET]: "#e0503f",
    [Game.VIOLET]: "#7939b1",
}

export const gameToTextColor: Record<Game, string> = {
    [Game.RED]: "black",
    [Game.BLUE]: "white",
    [Game.YELLOW]: "black",
    [Game.GOLD]: "black",
    [Game.SILVER]: "black",
    [Game.CRYSTAL]: "black",
    [Game.RUBY]: "white",
    [Game.SAPPHIRE]: "white",
    [Game.EMERALD]: "white",
    [Game.FIRERED]: "black",
    [Game.LEAFGREEN]: "black",
    [Game.DIAMOND]: "black",
    [Game.PEARL]: "black",
    [Game.PLATINUM]: "black",
    [Game.HEARTGOLD]: "black",
    [Game.SOULSILVER]: "black",
    [Game.BLACK]: "white",
    [Game.WHITE]: "black",
    [Game.BLACK_2]: "white",
    [Game.WHITE_2]: "black",
    [Game.X]: "white",
    [Game.Y]: "white",
    [Game.OMEGA_RUBY]: "white",
    [Game.ALPHA_SAPPHIRE]: "white",
    [Game.SUN]: "black",
    [Game.MOON]: "black",
    [Game.ULTRA_SUN]: "white",
    [Game.ULTRA_MOON]: "white",
    [Game.LETS_GO_PIKACHU]: "black",
    [Game.LETS_GO_EEVEE]: "black",
    [Game.SWORD]: "white",
    [Game.SHIELD]: "white",
    [Game.BRILLIANT_DIAMOND]: "black",
    [Game.SHINING_PEARL]: "black",
    [Game.LEGENDS_ARCEUS]: "white",
    [Game.SCARLET]: "white",
    [Game.VIOLET]: "white",
}
